#!/bin/bash
set -e -x

check_version() {
    if [ -z "$VERSION" ]; then
        echo "RANCHEROS_VERSION must be set"
        exit 1
    fi
}

PACKER_BUILDER_TYPE=${PACKER_BUILDER_TYPE:?"PACKER_BUILDER_TYPE is not set"}

echo "type: $PACKER_BUILDER_TYPE"
echo "name: $PACKER_BUILD_NAME"
env
echo "----------------------------------------"

case $PACKER_BUILD_NAME in

    "amazon-rancher")
        echo "building amazon-rancher"
        cat >cloud-config.yml<<EOF
#cloud-config
rancher:
  resize_device: /dev/xvda
  services_include:
    rancher-server: true
  docker:
    engine: docker-1.12.6
EOF
        check_version
        sudo system-docker run --volumes-from=user-volumes --net=host --privileged rancher/os:${VERSION} -d /dev/xvda -t amazon-ebs-hvm -c $(pwd)/cloud-config.yml --no-reboot --debug -p /dev/xvda1 --append "rancher.cloud_init.datasources=[\"ec2\"]"
        exit 0
        ;;

    "amazon-ebs-ecs")
        echo "building amazon-ebs-ecs"
        cat >cloud-config.yml<<EOF
#cloud-config
rancher:
  services_include:
    amazon-ecs-agent: true
  modules: [ena]
EOF
        check_version
        sudo system-docker run --volumes-from=user-volumes --net=host --privileged rancher/os:${VERSION} -d /dev/xvda -t amazon-ebs-hvm -c $(pwd)/cloud-config.yml --no-reboot --debug -p /dev/xvda1 --append "rancher.cloud_init.datasources=[\"ec2\"]"
        exit 0
        ;;

    "aliyun-ecs")
        cat >cloud-config.yml<<EOF
#cloud-config
rancher:
  resize_device: /dev/vda
EOF
        echo "building aliyun-ecs"
        sudo ros install -d /dev/sda -c $(pwd)/cloud-config.yml --no-reboot --debug --append "rancher.hypervisor_service=false rancher.autologin=tty1 rancher.cloud_init.datasources=[\"aliyun\"]"
        exit 0
        ;;

    "qemu-googlecompute")
        cat >cloud-config.yml<<EOF
#cloud-config
rancher:
  resize_device: /dev/sda
  docker:
    extra_args: [--mtu, 1460]
  system_docker:
    extra_args: [--mtu, 1460]
EOF
        sudo ros install -d /dev/sda -c $(pwd)/cloud-config.yml --no-reboot --debug --append "console=ttyS0 rancher.autologin=ttyS0 printk.devkmsg=on rancher.cloud_init.datasources=[\"gce\"]"
        exit 0
        ;;

esac

case ${PACKER_BUILDER_TYPE} in

    "virtualbox-iso")
        cat >vagrant.yml<<EOF
#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQtYmH8jlVf4rH3G/N00pdoW/G8WMVBK+HLfNmJ8k3mPQ7rp0y47j0AoT8Jv2VN60LB9CrH1asCCJaO2qK73bHbLpdZW5Hpu1+oQeB2yimvVJkNti/OlppY2RFXCadFkjYpaBKZbCmS1JOPLa5VLtSNra6y/uN88OqtaDVcCq5/egqwafEpqlhd9zGOxeTYZQ9gdYCcdZvjK9ja0A+zk3Ou7/2KKW6kdGtgbN2MdPA6PATFIPzmLuMax5n8CG41xNWAfcsjj+xsiZN8LwWb6LTwMDyjTY9kZyR06j2FLaxaMlvx9Jivki60muxzjjyWJ4wI1OEAmuPZ8GY7SHz9Wrr vagrant insecure public key
EOF
        sudo ros install -d /dev/sda -f -c ./vagrant.yml --no-reboot
        ;;

    "amazon-ebs")
        echo "building amazon-ebs"
        cat >cloud-config.yml<<EOF
#cloud-config
rancher:
  modules: [ena]
EOF
        check_version
        sudo system-docker run --volumes-from=user-volumes --net=host --privileged rancher/os:${VERSION} -d /dev/xvda -t $PACKER_BUILD_NAME -c $(pwd)/cloud-config.yml --no-reboot --debug -p /dev/xvda1 --append "rancher.cloud_init.datasources=[\"ec2\"]"
        ;;

    *)
        echo "Unknown type" 1>&2
        exit 1
        ;;
esac
